"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""
from utils.series import fib
from utils.predicates import even

fibs = fib(lambda i, v: v < 4000000)
s = sum(filter(even, fibs))
print(s)


