"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and
D = |Pk − Pj| is minimised; what is the value of D?

3n² - n + 3m² - m = 3l² - l
3(n² + m²) - (n + m) = 3l² - l
3(n² + m² + 2mn) - (2mn + n + m) = 3(n+m)² - (2mn + n + m) = 3l²  - l
3"""


def pentagonals(upto):
    for n in range(1, upto):
        yield n * (3 * n - 1) // 2

limit = 100_000
pentas = list(pentagonals(2 * limit))
s = set(pentas)

for i in range(limit):
    for j in range(i+1, i + 1 + 10_000):
        if pentas[i] + pentas[j] in s and pentas[j] - pentas[i] in s:
            print(i, j, pentas[j] - pentas[i])
            break