"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from utils.numbers import triangle_number
from utils.numbers import pentagonal_number
from utils.numbers import hexagonal_number

for n in range(140, 100_000):
    h = hexagonal_number(n)
    t = triangle_number(2 * n - 1)
    if h != t:
        continue
    for m in range(n, n * 3 // 2):
        p = pentagonal_number(m)
        if p == h:
            print(n, 2 * n - 1, m)
        elif p > h:
            continue
